name: Deployment
on:
  repository_dispatch:
    types:
      - deploy-command

jobs:
  getTag:
    if: ${{ github.event.client_payload.pull_request.merged == true }}
    runs-on: self-hosted
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          fetch-depth: 0
      - name: Get the tags
        env:
          TAGS: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
        run: |
          echo "::set-output name=tags::$(echo $TAGS)"
        id: tags
  deploying:
    runs-on: self-hosted
    needs: getTag
    if: ${{ github.event.client_payload.pull_request.merged == true &&  needs.getTag.outputs.tags != '' }}
    strategy:
      matrix:
        target: [ansible-cpanel_shared, ansible-cpanel_reseller, ansible-cpanel_business, ansible-cpanel_cloud, ansible-cpanel_mail, ansible-cpanel_standard]
      max-parallel: 2
      fail-fast: false
    steps:
      - name: Deployment target
        run: |
          echo "${{ matrix.target }}"
          echo "${{ needs.getTag.outputs.tags }}"
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
