name: "Deploy playbook"
on:
  pull_request:
    types: closed

jobs:
  call_workflow:
    uses: ./.github/workflows/tags.yml
  Get_env:
    needs: call_workflow
    runs-on:
      - self-hosted
    steps:
      - name: Find tags
        run: |
          echo ${{ needs.call_workflow.outputs.DEPLOY_TAGS }}
          echo ${{ needs.call_workflow.outputs.TEST_TAGS }}
  Deploy:
    needs: call_workflow
    if: ${{ github.ref_name == github.event.repository.default_branch && github.event.pull_request.merged == true && needs.call_workflow.outputs.DEPLOY_TAGS != '' }}
    runs-on: self-hosted
    steps:
      - name: Deploy shared
        run: echo "Deployment"
