name: "Deploy playbook"
on:
  pull_request:
    types: closed

jobs:
  Deploy:
    if: ${{ github.ref_name == github.event.repository.default_branch && github.event.pull_request.merged == true}}
    runs-on: self-hosted
    steps:
      - name: Deploy shared
        run: echo "Deployment>>>"