# name: deployment
# on:
#   repository_dispatch:
#     types: [deploy-command]
# jobs:
#   get_tag:
#     runs-on: self-hosted
#     if: ${{ github.event.client_payload.pull_request.merged == true }}
#     outputs:
#       tags: ${{ steps.tags.outputs.tags }}
#     steps:
#       - uses: actions/checkout@v3
#       - name: Get the tags
#         env:
#           TAGS: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
#         run: |
#           echo "::set-output name=tags::$(echo $TAGS)"
#         id: tags
#   deployment:
#     runs-on: self-hosted
#     needs: get_tag
#     if: ${{ github.event.client_payload.pull_request.merged == true &&  needs.get_tag.outputs.tags != '' }}
#     strategy:
#       matrix:
#         target: [ansible-cpanel_shared, ansible-cpanel_reseller, ansible-cpanel_business, ansible-cpanel_cloud, ansible-cpanel_mail, ansible-cpanel_standard]
#     steps:
#       - name: Deployment target
#         run: |
#           echo "${{ matrix.target }}"
#           echo "${{ needs.get_tag.outputs.tags }}"
#       - name: Add reaction
#         uses: peter-evans/create-or-update-comment@v2
#         with:
#           comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
#           reaction-type: hooray
