name: integration test
on:
  repository_dispatch:
    types: 
      - test-command
      - deploy-command
jobs:
  call-reusable-workflow:
    if: ${{ github.event.client_payload.pull_request.merged == false }}
    uses:  mahfudza16/action-testing/.github/workflows/reusable-test.yml@main
