name: integration test
on:
  repository_dispatch:
    types: [test-command]
jobs:
  integration-test:
    runs-on: self-hosted
    if: ${{ github.event.client_payload.pull_request.merged == false }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          fetch-depth: 0
      - name: Get the tags
        env:
          TAGS: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
        run: |
          echo "::set-output name=tags::$(echo $TAGS)"
        id: tags
      - name: Print tags
        run: |
          echo "${{ steps.tags.outputs.tags }}"
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
