name: 'Lint and test'
on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  Check:
    runs-on:
      - self-hosted
    outputs:
      env_vars: ${{ steps.env_vars.outputs.env_vars }}
      pr_tag: ${{ fromJson(steps.env_vars.outputs.env_vars).PR_TAG }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .github/commitlint.config.js

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "playbooks/"

      # - name: Setup Python 3.7
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: '3.7'

      # - name: Cache Pip packages
      #   uses: tespkg/actions-cache@v1
      #   with:
      #     key: ${{ github.repository }}/pip-python37-${{ hashFiles('.github/requirements.txt') }}
      #     path: ~/.cache/pip
      #     use-fallback: false
      #     bucket: "${{ secrets.ORG_CACHE_S3_BUCKET }}"
      #     endpoint: "${{ secrets.ORG_CACHE_S3_ENDPOINT }}"
      #     secretKey: "${{ secrets.ORG_CACHE_AWS_SECRET_ACCESS_KEY }}"
      #     accessKey: "${{ secrets.ORG_CACHE_AWS_ACCESS_KEY_ID }}"

      - name: Install Pip packages
        run: |
          pip install --requirement .github/requirements.txt

      - name: Lint Yaml files
        run: |
          yamllint \
          --config-file .github/yamllint_config.yaml \
          --format github \
          --no-warnings \
          .

      - name: Get the tags
        run: |
          DEPLOY_TAGS=`echo '${{ github.event.head_commit.message }}' | awk '/Deploy-Tags/ {$1="";print}' | tr -d ' '`
          TEST_TAGS=`echo '${{ github.event.head_commit.message }}' | awk '/Test-Tags/ {$1="";print}' | tr -d ' '`

          if [ ! -z $DEPLOY_TAGS ]; then
            echo DEPLOY_TAGS=$DEPLOY_TAGS >> $GITHUB_ENV
            echo PR_TAG=DEPLOY_TAGS >> $GITHUB_ENV
          elif [ ! -z $TEST_TAGS ]; then
            echo TEST_TAGS=$TEST_TAGS >> $GITHUB_ENV
            echo PR_TAG=TEST_TAGS >> $GITHUB_ENV
          fi

      - name: Set env vars as output
        run: |
          echo "::set-output name=env_vars::$(echo $(jq -n 'env'))"
        id: env_vars

  Run_PR_and_test:
    needs: Check
    if: ${{ github.ref_name != github.event.repository.default_branch && ( fromJson(needs.Check.outputs.env_vars).DEPLOY_TAGS != '' || fromJson(needs.Check.outputs.env_vars).TEST_TAGS != '' ) }}
    runs-on:
      - self-hosted
    steps:
      - name: run PR and test
        run: echo "${{ (needs.Check.outputs.pr_tag == 'DEPLOY_TAGS' && fromJson(needs.Check.outputs.env_vars).DEPLOY_TAGS) || 'Testing' }}"
