name: 'Lint and test'
on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  Check:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check
        run: |
          echo '${{ toJson(github) }}'

      - name: Lint commit message
        id: commit_lint
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .github/commitlint.config.js
        continue-on-error: true

      - name: Run ansible-lint
        id: ansible_lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "playbooks/"
        continue-on-error: true

      # - name: Setup Python 3.7
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: '3.7'

      # - name: Cache Pip packages
      #   uses: tespkg/actions-cache@v1
      #   with:
      #     key: ${{ github.repository }}/pip-python37-${{ hashFiles('.github/requirements.txt') }}
      #     path: ~/.cache/pip
      #     use-fallback: false
      #     bucket: "${{ secrets.ORG_CACHE_S3_BUCKET }}"
      #     endpoint: "${{ secrets.ORG_CACHE_S3_ENDPOINT }}"
      #     secretKey: "${{ secrets.ORG_CACHE_AWS_SECRET_ACCESS_KEY }}"
      #     accessKey: "${{ secrets.ORG_CACHE_AWS_ACCESS_KEY_ID }}"

      - name: check python version
        id: python_check
        run: |
          python --version
        continue-on-error: true

      - name: Install Pip packages
        id: install_packages
        run: |
          pip install --requirement .github/requirements.txt
        continue-on-error: true

      - name: Lint Yaml files
        id: yaml_lint
        run: |
          yamllint \
          --config-file .github/yamllint_config.yaml \
          --format github \
          --no-warnings \
          .
        continue-on-error: true

      - name: check the failed steps
        run: |
          echo "::set-output name=steps_fails::$(echo '${{ toJson(steps) }}'| jq 'to_entries[]|select(.value.outcome=="failure").key' | tr -d '"')"
        id: steps_fails

      - name: Create comment if any previous step of job failed
        if: steps.steps_fails.outputs.steps_fails != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Test failed:
            ```
              ${{ steps.steps_fails.outputs.steps_fails }}
            ```
          reaction-type: confused
