name: 'Lint and test'
on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  Check:
    runs-on:
      - self-hosted
    outputs:
      env_vars: ${{ steps.env_vars.outputs.env_vars }}
      pr_tag: ${{ fromJson(steps.env_vars.outputs.env_vars).PR_TAG }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commit message
        id: commit_lint
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .github/commitlint.config.js

      - name: Run ansible-lint
        id: ansible_lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "playbooks/"

      # - name: Setup Python 3.7
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: '3.7'

      # - name: Cache Pip packages
      #   uses: tespkg/actions-cache@v1
      #   with:
      #     key: ${{ github.repository }}/pip-python37-${{ hashFiles('.github/requirements.txt') }}
      #     path: ~/.cache/pip
      #     use-fallback: false
      #     bucket: "${{ secrets.ORG_CACHE_S3_BUCKET }}"
      #     endpoint: "${{ secrets.ORG_CACHE_S3_ENDPOINT }}"
      #     secretKey: "${{ secrets.ORG_CACHE_AWS_SECRET_ACCESS_KEY }}"
      #     accessKey: "${{ secrets.ORG_CACHE_AWS_ACCESS_KEY_ID }}"

      - name: check python version
        id: python_check
        run: |
          python --version

      - name: Install Pip packages
        id: install_packages
        run: |
          pip install --requirement .github/requirements.txt

      - name: Lint Yaml files
        id: yaml_lint
        run: |
          yamllint \
          --config-file .github/yamllint_config.yaml \
          --format github \
          --no-warnings \
          .

      # - name: Create comment if any previous step of job failed
      #   if: ${{ failure() }}
      #   uses: peter-evans/create-or-update-comment@v2
      #   with:
      #     issue-number: ${{ github.event.pull_request.number }}
      #     body: |
      #       > Deployed on
      #     reaction-type: confused
      - name: check
        run: |
          echo '${{ toJson(steps) }}'

