name: 'Lint, run and test'
on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  call_workflow:
    uses: ./.github/workflows/tags.yml@testing_again
    steps:
      - run: echo ${{ outputs.DEPLOY_TAGS }}
      - run: echo ${{ outputs.TEST_TAGS }}

  Check:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .github/commitlint.config.js

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "playbooks/"

      # - name: Setup Python 3.7
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: '3.7'

      # - name: Cache Pip packages
      #   uses: tespkg/actions-cache@v1
      #   with:
      #     key: ${{ github.repository }}/pip-python37-${{ hashFiles('.github/requirements.txt') }}
      #     path: ~/.cache/pip
      #     use-fallback: false
      #     bucket: "${{ secrets.ORG_CACHE_S3_BUCKET }}"
      #     endpoint: "${{ secrets.ORG_CACHE_S3_ENDPOINT }}"
      #     secretKey: "${{ secrets.ORG_CACHE_AWS_SECRET_ACCESS_KEY }}"
      #     accessKey: "${{ secrets.ORG_CACHE_AWS_ACCESS_KEY_ID }}"

      - name: Install Pip packages
        run: |
          pip install --requirement .github/requirements.txt

      - name: Lint Yaml files
        run: |
          yamllint \
          --config-file .github/yamllint_config.yaml \
          --format github \
          --no-warnings \
          .

