name: Pull request merged
on:
  pull_request:
    types: closed

jobs:
  creatingCommentIfNeeded:
    runs-on: self-hosted
    if: github.ref_name == github.event.repository.default_branch && github.event.pull_request.merged == true
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
    steps:
      # - uses: actions/checkout@v3
      # - name: check
      #   run: |
      #     echo '${{ toJson(github) }}'
      # - name: check
      #   env:
      #     BODY: ${{ github.event.pull_request.body }}
      #   run: |
      #     echo "::set-output name=body::$(echo $BODY)"
      #   id: find
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: /deploy
          direction: last
      - name: Get the tags
        if: steps.fc.outputs.comment-id != ''
        run: |
          tags=$(echo ${{ steps.fc.outputs.comment-body }} | awk '/\deploy/ {$1="";print}' | tr -d ' ')
          echo "::set-output name=tags::$(echo $tags)"
        id: tags
      - name: Create comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.HELLO }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.tags.outputs.tags }}
