name: Deployment request
on:
  pull_request:
    types: closed

jobs:
  get_tag:
    runs-on: self-hosted
    if: ${{ github.ref_name == github.event.repository.default_branch && github.event.pull_request.merged == true }}
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
    steps:
      - uses: actions/checkout@v3
      - name: Find tags
        uses: peter-evans/find-comment@v2
        id: find
        with:
          issue-number: 1
          body-includes: /deploy
      - name: Get the tags
        run: |
          tags=$(echo ${{ steps.find.outputs.comment-body }} | awk '/\deploy/ {$1="";print}' | tr -d ' ')
          echo "::set-output name=tags::$(echo $tags)"
        id: tags

  deployment:
    runs-on: self-hosted
    needs: get_tag
    if: ${{ github.ref_name == github.event.repository.default_branch &&  github.event.pull_request.merged == true &&  needs.get_tag.outputs.tags != '' }}
    strategy:
      matrix:
        target: [ansible-cpanel_shared, ansible-cpanel_reseller, ansible-cpanel_business, ansible-cpanel_cloud, ansible-cpanel_mail, ansible-cpanel_standard]
    steps:
      - name: Deployment target
        run: |
          echo "${{ matrix.target }}"
          echo "${{ needs.get_tag.outputs.tags }}"
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
