name: Reusable test
on: 
  workflow_call:
    secrets:
      ssh_private_key:
        required: true

jobs:
  getTag:
    runs-on: self-hosted
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
    steps:
      - name: test
        run: |
          echo '${{ toJson(github) }}'
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          fetch-depth: 0
      - name: Get the tags
        env:
          TAGS: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
        run: |
          echo "::set-output name=tags::$(echo $TAGS)"
        id: tags
  testing:
    needs: getTag
    runs-on: self-hosted
    if: ${{ needs.getTag.outputs.tags != '' }}
    steps:
      - name: Print tags
        run: |
          echo "${{ needs.getTag.outputs.tags }}"
      - name: Print ref_name
        run: |
          echo "${{ github.event.client_payload.pull_request.head.ref }}"
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > Integration test successful!
          reaction-type: hooray
