name: run-pr-command
on:
  repository_dispatch:
    types: [run-pr-command]
jobs:
  runPr:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
