name: 'Get tags'
on:
  workflow_call:
    outputs:
      DEPLOY_TAGS:
        description: Deploy tags
        value: ${{ fromJson(jobs.env.outputs.env_vars).DEPLOY_TAGS }}
      TEST_TAGS:
        description: Test tags
        value: ${{ fromJson(jobs.env.outputs.env_vars).TEST_TAGS }}

jobs:
  env:
    runs-on:
      - self-hosted
    outputs:
      env_vars: ${{ steps.env_vars.outputs.env_vars }}
    steps:
      - name: Find tags
        run: |
          echo "DEPLOY_TAGS=`echo '${{ github.event.head_commit.message }}' | awk '/Deploy-Tags/ {$1="";print}'`" >> $GITHUB_ENV
          echo "TEST_TAGS=`echo '${{ github.event.head_commit.message }}' | awk '/Test-Tags/ {$1="";print}'`" >> $GITHUB_ENV
      - name: Print env var
        run: |
          echo "::set-output name=env_vars::$(echo $(jq -n 'env'))"
        id: env_vars
