name: integration test
on:
  repository_dispatch:
    types: [integration-test-command]
jobs:
  runPr:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: run PR and test
        #if: ${{ github.ref_name != github.event.repository.default_branch }}
        run: echo ${{ toJSON(fromJSON(github)) }}
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
